name: Update Crypto Data

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pycoingecko numpy

      - name: Run script
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: python3 main.py
