name: Update Crypto Data
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run update script
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: python main.py
